### ISSUE TITLE
Background windows gets minimized when moving topmost window

### ISSUE THREAD

**Issue by thiagomeireless** [koekeishiya/yabai#1809]
I am not sure if this is a bug or a feature (that I would love to disable), but what happens is:

- I have an application open, e.g.: Firefox
- I open another application in the same space, that is set to float and sticky, e.g.: Finder
- I try to use the `mouse_modifier` + `mouse_action1` (move) to move this float application and have 2 different outcomes depending if the application is focused or not:
  - If it's the currently focused window, I can move it as expected and nothing happens to the background applications
  - If it's NOT the currently focused window (e.g.: I clicked the background window), when I try to move it, all the background applications are minimized. <- this is what I want to fix/disable

Here's a video showing what happens:

https://github.com/koekeishiya/yabai/assets/6698296/6be13e25-4faf-4b8d-984e-d29db18212f2

**Comment by koekeishiya** [comment]
I believe this is macOS system behaviour that interferes. What is the value of your `mouse_modifier`?
Try to set it to `fn` or `ctrl` and see if you can reproduce the issue.

**Comment by thiagomeireless** [comment]
Hey @koekeishiya thanks for the quick reply! I never thought the `mouse_modifier` would be the problem, but it is.

This only happens when using the `alt` modifier. I tested with `ctrl` and `cmd` and both worked fine (didn't test with `fn` as I use an external keyboard with only 3 left modifiers)

Do you have any idea on how could I prevent it from triggering when using `alt` modifier?

**Comment by thiagomeireless** [comment]
I see. Sadly I don't have much C experience to try messing around with it, but as I can change the `mouse_modifier` to another key and it works fine, feel free to close the issue if you feel like it.

I would still love to be able to use the desired `alt` modifier, of course 😅

**Comment by koekeishiya** [comment]
You can change this line https://github.com/koekeishiya/yabai/blob/master/src/mouse_handler.c#L267 from

>  mouse_state->handle = CGEventTapCreate(kCGAnnotatedSessionEventTap, kCGHeadInsertEventTap, kCGEventTapOptionDefault, mask, mouse_handler, mouse_state);

to

> mouse_state->handle = CGEventTapCreate(kCGHIDEventTap, kCGHeadInsertEventTap, kCGEventTapOptionDefault, mask, mouse_handler, mouse_state);

and it will fix your problem, but it will revert other fix mentioned in #1378

**Comment by koekeishiya** [comment]
Fixed on master.

**Comment by koekeishiya** [comment]
Fixed in v7.0.0.

**Comment by thiagomeireless** [comment]
Hey @koekeishiya sorry for the ping on a closed issue, but I just upgrade and everything seems to be working well, except now the `resize` feature (`mouse_modifier` + `mouse_action2`) is not working. Trying with `alt` and `cmd` and problem persists.

Is there something I might be missing to configure in this new released version? No error logs:

```
❯ cat /tmp/yabai_thiago.out.log
yabai configuration loaded..
yabai configuration loaded..
yabai configuration loaded..

❯ cat /tmp/yabai_thiago.err.log
(empty)
```

**Comment by koekeishiya** [comment]
asfd of course changing from AnnotatedSessionTap to HIDTap changes the timestep of reported in events causing the resize throttling to change completely... without that code ever being touched.

**Comment by koekeishiya** [comment]
https://github.com/koekeishiya/yabai/issues/2160
