### ISSUE TITLE
Unmanaged window full-screen when yabai restarts

### ISSUE THREAD

**Issue by szfkamil** [koekeishiya/yabai#2307]
I have had this issue for a while now. A lot of unmanaged windows get full-screen'd when yabai restarts. Output of `yabai -m rule --list` for two of the apps that have this issue:

```
{
	"index":30,
	"label":"",
	"app":"^Firefox$",
	"title":"",
	"role":"",
	"subrole":"",
	"display":0,
	"space":0,
	"follow_space":false,
	"opacity":0.0000,
	"manage":false,
	"sticky":null,
	"mouse_follows_focus":null,
	"sub-layer":"",
	"native-fullscreen":null,
	"grid":"0:0:0:0:0:0",
	"scratchpad":"",
	"one-shot":false,
	"flags":"0x00000001"
}

{
	"index":6,
	"label":"",
	"app":"^iTerm2$",
	"title":"",
	"role":"",
	"subrole":"",
	"display":0,
	"space":3,
	"follow_space":false,
	"opacity":0.0000,
	"manage":false,
	"sticky":null,
	"mouse_follows_focus":null,
	"sub-layer":"",
	"native-fullscreen":null,
	"grid":"0:0:0:0:0:0",
	"scratchpad":"",
	"one-shot":false,
	"flags":"0x00000001"
}
```

**Comment by evanaze** [comment]
Nice config! Definitely got some ideas from it. What version are you using? I had a similar issue in `7.1.0`, but it was fixed when I updated to `7.1.1`.

**Comment by szfkamil** [comment]
Here is a file with logs: https://d1ysz50cxb9zwl.cloudfront.net/WUSOJJHcLE5Z_o4Cju1YsdzRXwsVHc3FnjBo62SPOJNNIZznDJCjx7jBdDTx99Q6/by/40522061/as/file.txt?Expires=1718038533&Signature=Zaxg9ilmyXtGMHOvN-8qUYPBZxjqdUuCYFyMDuy~0TwhVaGJcK85M5ziZks1G-Hkmw~S9pVs8yrOlA7-Ca4CIcfe12eO1i~e4u30UvTbWBdw5cufdEUxwtq4QqFmVekFLZVsnJsfDmno4BiZaTd-NEPvv2rZJnN-eT33gtfUxLEvBe2g~zzwQQkFS3NwSoI0Q9la74NjKtbKPkOiYBYInWf5MN16jxiXNWDoV83q35rTI9SFZ97OMF~No36aBTGljZgulKmy8BtvyAmD0j2WlD7~ILyJZTwduEfuMNYkBTHWqsSoTSrRWrPnaFQUZHlcl5G3Ze2jX2RQgClsI2XoWw__&Key-Pair-Id=APKAJAERRT46LD6FN4NA

**Comment by szfkamil** [comment]
```
1:

{
	"index":21,
	"label":"",
	"app":"^Obsidian$",
	"title":"",
	"role":"",
	"subrole":"",
	"display":0,
	"space":0,
	"follow_space":false,
	"opacity":1.0000,
	"manage":true,
	"sticky":null,
	"mouse_follows_focus":null,
	"sub-layer":"",
	"native-fullscreen":null,
	"grid":"0:0:0:0:0:0",
	"scratchpad":"",
	"one-shot":false,
	"flags":"0x00020001"
}

2:

{
	"index":31,
	"label":"",
	"app":"^Obsidian$",
	"title":"",
	"role":"",
	"subrole":"",
	"display":0,
	"space":0,
	"follow_space":false,
	"opacity":0.0000,
	"manage":false,
	"sticky":null,
	"mouse_follows_focus":null,
	"sub-layer":"",
	"native-fullscreen":null,
	"grid":"0:0:0:0:0:0",
	"scratchpad":"",
	"one-shot":false,
	"flags":"0x00000001"
}

These two are the two first instances of mention of Obsidian after —rule —list. The following two are after Obsidian resized.

3:

{
	"index":21,
	"label":"",
	"app":"^Obsidian$",
	"title":"",
	"role":"",
	"subrole":"",
	"display":0,
	"space":0,
	"follow_space":false,
	"opacity":1.0000,
	"manage":true,
	"sticky":null,
	"mouse_follows_focus":null,
	"sub-layer":"",
	"native-fullscreen":null,
	"grid":"0:0:0:0:0:0",
	"scratchpad":"",
	"one-shot":false,
	"flags":"0x00020001"

}



4:

{
	"index":31,
	"label":"",
	"app":"^Obsidian$",
	"title":"",
	"role":"",
	"subrole":"",
	"display":0,
	"space":0,
	"follow_space":false,
	"opacity":0.0000,
	"manage":false,
	"sticky":null,
	"mouse_follows_focus":null,
	"sub-layer":"",
	"native-fullscreen":null,
	"grid":"0:0:0:0:0:0",
	"scratchpad":"",
	"one-shot":false,
	"flags":"0x00000001"
}


Output of debug log:

EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_WINDOW_MOVED:DEBOUNCED Obsidian 72
EVENT_HANDLER_DAEMON_MESSAGE: rule --apply
yabai configuration loaded...
EVENT_HANDLER_APPLICATION_FRONT_SWITCHED: iTerm2 (3796)
EVENT_HANDLER_APPLICATION_FRONT_SWITCHED: iTerm2 has windows that are not yet resolved
EVENT_HANDLER_SPACE_CHANGED: 6
space_manager_refresh_application_windows: Firefox has windows that are not yet resolved
space_manager_refresh_application_windows: Todoist has windows that are not yet resolved
space_manager_refresh_application_windows: TextEdit has windows that are not yet resolved
space_manager_refresh_application_windows: iTerm2 has windows that are not yet resolved
window_manager_create_and_add_window:415 iTerm2 - kamil@Mac-mini:~ (AXWindow:AXStandardWindow:1)
window_manager_create_and_add_window:853 iTerm2 - kamil@Mac-mini:~ (AXWindow:AXStandardWindow:1)
window_manager_create_and_add_window:601 iTerm2 - man yabai (AXWindow:AXStandardWindow:1)
window_manager_create_and_add_window:215 iTerm2 - tail -f /tmp/yabai_$USER.err.log (AXWindow:AXStandardWindow:1)
window_manager_add_existing_application_windows: all windows for iTerm2 are now resolved
EVENT_HANDLER_WINDOW_FOCUSED: iTerm2 415
EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 415
EVENT_HANDLER_DAEMON_MESSAGE: space --focus 1
EVENT_HANDLER_APPLICATION_FRONT_SWITCHED: Obsidian (1649)
EVENT_HANDLER_SPACE_CHANGED: 4
space_manager_refresh_application_windows: Firefox has windows that are not yet resolved
space_manager_refresh_application_windows: Todoist has windows that are not yet resolved
space_manager_refresh_application_windows: TextEdit has windows that are not yet resolved
EVENT_HANDLER_MOUSE_DOWN: 3422.17, 26.18
EVENT_HANDLER_MOUSE_DRAGGED: 3421.45, 26.53
EVENT_HANDLER_MOUSE_DRAGGED: 3418.13, 27.36
EVENT_HANDLER_MOUSE_DRAGGED: 3402.54, 28.77
EVENT_HANDLER_MOUSE_DRAGGED: 3379.94, 31.79
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 3353.84, 33.32
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 3329.49, 34.84
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 3299.89, 36.39
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 3272.04, 36.39
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 3240.68, 36.39
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 3202.31, 37.99
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 3159.73, 37.99
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 3124.86, 37.99
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 3088.25, 39.58
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 3051.64, 39.58
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 3013.27, 39.58
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2990.67, 39.58
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2961.07, 41.14
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2934.96, 41.14
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2922.88, 42.48
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2903.79, 42.48
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2895.20, 42.48
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2890.13, 43.49
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2886.80, 43.49
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2886.45, 43.84
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_UP: 2886.45, 43.84
EVENT_HANDLER_MOUSE_DOWN: 2886.45, 43.84
EVENT_HANDLER_MOUSE_DRAGGED: 2886.09, 44.20
EVENT_HANDLER_MOUSE_DRAGGED: 2884.52, 44.72
EVENT_HANDLER_MOUSE_DRAGGED: 2874.18, 49.88
EVENT_HANDLER_MOUSE_DRAGGED: 2863.85, 53.75
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2850.02, 59.29
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2832.39, 66.62
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2814.77, 73.96
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2797.43, 79.74
EVENT_HANDLER_MOUSE_DRAGGED: 2779.80, 87.08
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2758.96, 94.52
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2745.12, 100.05
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2720.55, 109.27
EVENT_HANDLER_WINDOW_RESIZED:DEBOUNCED Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2701.46, 115.14
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2678.86, 122.67
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2649.07, 135.21
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2626.25, 145.86
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2586.94, 162.23
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2539.43, 182.32
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2509.64, 193.30
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2481.79, 202.58
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2443.28, 215.41
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DREVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_DAEMON_MESSAGE: rule --apply
yabai configuration loaded...
EVENT_HANDLER_MOUSE_DOWN: 3422.93, 182.89
EVENT_HANDLER_MOUSE_DRAGGED: 3419.61, 184.55
EVENT_HANDLER_MOUSE_DRAGGED: 3412.78, 187.96
EVENT_HANDLER_MOUSE_DRAGGED: 3383.17, 195.75
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 3358.82, 201.84
EVENT_HANDLER_MOUSE_DRAGGED: 3325.71, 208.14
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_WINDOW_RESIZED:DEBOUNCED Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 3296.11, 211.26
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 3261.25, 212.84
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 3229.89, 214.41
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 3195.03, 214.41
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 3167.18, 212.86
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 3127.06, 212.86
EVENT_HANDLER_MOUSE_DRAGGED: 3095.70, 212.86
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_WINDOW_RESIZED:DEBOUNCED Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 3064.35, 212.86
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 3040.00, 212.86
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 3017.40, 212.86
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 3001.81, 212.86
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2994.98, 212.86
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2989.91, 213.87
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_DRAGGED: 2989.20, 213.87
EVENT_HANDLER_WINDOW_RESIZED: Obsidian 72
EVENT_HANDLER_MOUSE_UP: 2989.20, 213.87
EVENT_HANDLER_DAEMON_MESSAGE: space --focus 3
EVENT_HANDLER_APPLICATION_FRONT_SWITCHED: iTerm2 (3796)
EVENT_HANDLER_APPLICATION_FRONT_SWITCHED: iTerm2 has windows that are not yet resolved
window_manager_create_and_add_window:415 iTerm2 - tail -f /tmp/yabai_$USER.out.log (AXWindow:AXStandardWindow:1)
window_manager_create_and_add_window:853 iTerm2 - kamil@Mac-mini:~ (AXWindow:AXStandardWindow:1)
window_manager_create_and_add_window:601 iTerm2 - man yabai (AXWindow:AXStandardWindow:1)
window_manager_create_and_add_window:215 iTerm2 - tail -f /tmp/yabai_$USER.err.log (AXWindow:AXStandardWindow:1)
window_manager_add_existing_application_windows: all windows for iTerm2 are now resolved
EVENT_HANDLER_SPACE_CHANGED: 6
space_manager_refresh_application_windows: Firefox has windows that are not yet resolved
space_manager_refresh_application_windows: Todoist has windows that are not yet resolved
space_manager_refresh_application_windows: TextEdit has windows that are not yet resolved

```

**Comment by szfkamil** [comment]
> Nice config! Definitely got some ideas from it. What version are you using? I had a similar issue in `7.1.0`, but it was fixed when I updated to `7.1.1`.

I am still experiencing the issue after updating OS *and* binary. Would you mind sharing your config? Maybe looking at it can suggest something.
