### ISSUE TITLE
Cannot move window to space on macOS Sequoia (15.1)

### ISSUE THREAD

**Issue by twilightty** [koekeishiya/yabai#2441]
Hi, I'm having an issue where I can't move my window to other space with this command: `yabai -m window --space  3`

If I execute this, yabai will just move the window lower, and it refuses to move that window to the workspace.

Any idea?

fwiw
```
$ yabai -v
yabai-v7.1.3
```

Also, if I give `sudo yabai --load-sa` a try, I get this error: 
<img width="396" alt="image" src="https://github.com/user-attachments/assets/98d530c6-9bcb-4ed5-b622-e3a956dc61ab">

**Comment by ZyberSE** [comment]
I have the same issue on Sequoia 15.0.

**Comment by ramonvg** [comment]
Same issue on Sequoia 15.0.

**Comment by twilightty** [comment]
Well in theory 15.0 should be working just fine, have you guys tried installing from HEAD?

**Comment by ZyberSE** [comment]
I have not, is there some information how that's done? I've installed, and are updating through brew.

**Comment by twilightty** [comment]
Have a look: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)

**Comment by ddr5ecc** [comment]
I just update to sequoia 15.0 and yabai-v7.1.4 from HEAD. 
However, it still cannot move windows to another space.

**Comment by ddr5ecc** [comment]
> Have you disabled SIP according to the [docs](https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection)?

Not yet. Thank you for the instruction. I believe that is the reason!

**Comment by kmiterror** [comment]
@ZyberSE 
Yes, macOS 15 requires partial SIP disabling.

**Comment by Holer90** [comment]
> @ZyberSE Yes, macOS 15 requires partial SIP disabling.

Is there any way around this? 

Similar to @ZyberSE company policies do not allow me to disable SIP.

**Comment by tshu-w** [comment]
> Yes, macOS 15 requires partial SIP disabling.

I'd like to know if this was mentioned somewhere. I tried searching the changelog, but couldn't find it.

**Comment by kmiterror** [comment]
There is this snippet in the changelog
## [7.1.2] - 2024-08-10
### Changed
- Moving windows to other spaces requires SIP to be disabled on macOS Sequoia [#2324](https://github.com/koekeishiya/yabai/issues/2324) [#2331](https://github.com/koekeishiya/yabai/issues/2331)

**Comment by GiveNoCode** [comment]
Same issue on macOS 15
SIP disabled and installed from HEAD did not help.

moving to another display causes other windows to resize as if  target window has moved but actually it stays in place

note: on displays detup  command works as long as space target space is active on another display

**Comment by twilightty** [comment]
hey, you can try out `yabai --load-sa`, and make sure the Dock isn't restarted during the process.

**Comment by ZyberSE** [comment]
I disabled SIP on macOS 15.01 and what do you know... it WORKS!! What a f-ing relief! Finally I can work again! 🤩
Didn't install from HEAD, just the same version that comes from brew.

**Comment by ramonvg** [comment]
Same here, the reason it was not working was that I didn't disable SIP. Thanks everyone for the help 🙏

**Comment by chrede88** [comment]
> Hi, I'm having an issue where I can't move my window to other space with this command: `yabai -m window --space 3`
> 
> If I execute this, yabai will just move the window lower, and it refuses to move that window to the workspace.
> 
> Any idea?
> 
> fwiw
> 
> ```
> $ yabai -v
> yabai-v7.1.3
> ```
> 
> Also, if I give `sudo yabai --load-sa` a try, I get this error: <img alt="image" width="396" src="https://private-user-images.githubusercontent.com/80335335/371821195-98d530c6-9bcb-4ed5-b622-e3a956dc61ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMjUyNTksIm5iZiI6MTcyODMyNDk1OSwicGF0aCI6Ii84MDMzNTMzNS8zNzE4MjExOTUtOThkNTMwYzYtOWJjYi00ZWQ1LWI2MjItZTNhOTU2ZGM2MWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDE4MTU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4MWVlYjk5MzYzYWMyMzIxMGY1MDllN2NmMmY1MmVkOTJmODg5MjdmY2JlMjY3Zjk5OTI4MGJlZDE5ZDNmMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fc_YNnBs0FrYVlG7xgJGIwWPXT6V_DEIJz7hYdxmqj0">

Maybe you forgot to update the hash in the sudoer file after updating yabai?

**Comment by Ahmad-Vakilzadeh** [comment]
> Same issue on macOS 15 SIP disabled and installed from HEAD did not help.
> 
> moving to another display causes other windows to resize as if target window has moved but actually it stays in place
> 
> note: on displays detup command works as long as space target space is active on another display

same here disabled sip partially according to the docs and still have the problem

**Comment by OverVlad** [comment]
@twilightty I updated it to the latest Yabai and am still experiencing this issue.

Yabai: yabai-v7.1.4
MacOS: 15.0.1

This command doesn't work
yabai -m window --space next

Do you know if I am missing something?

**Comment by twilightty** [comment]
> @twilightty I updated it to the latest Yabai and am still experiencing this issue.
> 
> Yabai: yabai-v7.1.4 MacOS: 15.0.1
> 
> This command doesn't work yabai -m window --space next
> 
> Do you know if I am missing something?

Try running `sudo yabai --load-sa`
