### ISSUE TITLE
Transparency not working on macOS Big Sur

### ISSUE THREAD

**Issue by kabirbg** [koekeishiya/yabai#726]
Window transparency seems to be set to 1.00 for all windows on macOS Big Sur. I'm running macOS 11.0.1 and yabai-v3.3.4; my yabai config is working because whenever I change anything else in it and restart yabai, the config reloads. However, I currently have transparency set to 0.8 for normal windows and 0.9 for active windows in the config, but this isn't reflected in the actual windows. The same settings were working fine in Catalina (10.15.7). I'm not sure if this is an issue with yabai, or something I'm doing wrong.
Apologies but this is my first issue so I don't know what log files or screenshots or any such thing would be helpful to attach.
Thanks.

**Comment by maishams** [comment]
i have the same issue as well!

**Comment by maishams** [comment]
oh i just fixed mine! 
run the commands :
sudo yabai --uninstall-sa
sudo yabai --install-sa
sudo yabai --load-sa
brew services restart yabai

(this reinstalls the scripting addition and then restarts yabai)
hope this helped :)

**Comment by koekeishiya** [comment]
See https://github.com/koekeishiya/yabai/issues/589#issuecomment-727195802 
and/or 
https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)

**Comment by dnordberg** [comment]
After having upgrade to Big Sur opacity doesn't seem to affect any windows.

I've uninstalled yabai, disabled SIP again, edited /private/etc/sudoers.d/yabai and ~/.yabai to run the Big Sur required changes, reinstalled everything, and it still doesn't work.

I have a few log file lines:

```
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
'window_opacity_duration' cannot be changed on macOS Catalina/Big Sur because of an Apple bug in the WindowServer
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
'window_opacity_duration' cannot be changed on macOS Catalina/Big Sur because of an Apple bug in the WindowServer
```

My ~/.yabai config:

```
#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.70
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
...
```

csrutil status
```
/ $ csrutil status
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled
	BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```
